### ISSUE TITLE
Can't output more than one item per side

### ISSUE THREAD

**Issue by Tobanyi** [lukebemish/simple_buffers#1]
If a machine/chest is attached to the side of a buffer and more than one item is set up to be output to it, it will only output one of the items not both.

Settings: output two different items, item limit of 1, auto-push enabled.

**Comment by lukebemish** [comment]
What items are in the buffer at the time?

**Comment by lukebemish** [comment]
And can you give me the version and a screenshot?

**Comment by lukebemish** [comment]
May add some more filtering options related to this; see #2

**Comment by Tobanyi** [comment]
Thanks.  I changed it to how you said and it worked.  I just didn't understand the effects of the options, I suppose (I thought that one item means one of each filtered item).
